import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home(props: { testProducts: IProduct[] }): JSX.Element {
  return (
    <div className={styles.container}>
      <Head>
        {console.log(props)}
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

interface IProduct {
  id: string
  name: string
  price: number
  url: string
  description: string
  image: string
}

export async function getStaticProps(): Promise<{
  props: {
    testProducts: IProduct[]
  }
}> {
  const testProducts = [
    {
      id: 'nextjs_halfmoon',
      name: 'Halfmoon Betta',
      price: 25.0,
      image: '../static/halfmoon.jpg',
      description:
        'The Halfmoon betta is arguably one of the prettiest betta species. It is recognized by its large tail that can flare up to 180 degrees.',
    } as IProduct,
    {
      id: 'nextjs_dragonscale',
      name: 'Dragon Scale Betta',
      price: 35,
      image: '../static/dragonscale.jpg',
      description:
        'The dragon scale betta is a rarer and higher maintenance fish. It is named by its thick white scales covering his sides that looks like dragon scale armor.',
    } as IProduct,
    {
      id: 'nextjs_crowntail',
      name: 'Crowntail Betta',
      price: 7.5,
      image: '../static/crowntail.jpg',
      description:
        "The crowntail is pretty common, but interesting none the less. It's recognized by the shape of its tail that has an appearance of a comb.",
    } as IProduct,
    {
      id: 'nextjs_veiltail',
      name: 'Veiltail Betta',
      price: 5.0,
      image: '../static/veiltail.jpg',
      description:
        'By far the most common betta fish. You can recognize it by its long tail aiming downwards.',
    } as IProduct,
  ]

  return { props: { testProducts } }
}
